name:                megaparsec-csv
version:             0.1.0.0
github:              "noahmartinwilliams/megaparsec-csv"
license:             BSD-3-Clause
author:              "Noah Martin Williams"
maintainer:          "noahmartinwilliams@gmail.com"
copyright:           "GPL"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            A simple megaparsec library for CSV files with optional escape characters.
# category:            Web

description:         A Simple megaparsec library for parsing CSV data with optional escape characters.

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - megaparsec


